// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.dip.hakuro.twitserif.domain;

import java.util.List;
import jp.dip.hakuro.twitserif.domain.Serifs;
import jp.dip.hakuro.twitserif.domain.SerifsDataOnDemand;
import jp.dip.hakuro.twitserif.domain.SerifsIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SerifsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SerifsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SerifsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SerifsIntegrationTest: @Transactional;
    
    @Autowired
    private SerifsDataOnDemand SerifsIntegrationTest.dod;
    
    @Test
    public void SerifsIntegrationTest.testCountSerifses() {
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", dod.getRandomSerifs());
        long count = Serifs.countSerifses();
        Assert.assertTrue("Counter for 'Serifs' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SerifsIntegrationTest.testFindSerifs() {
        Serifs obj = dod.getRandomSerifs();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to provide an identifier", id);
        obj = Serifs.findSerifs(id);
        Assert.assertNotNull("Find method for 'Serifs' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Serifs' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void SerifsIntegrationTest.testFindAllSerifses() {
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", dod.getRandomSerifs());
        long count = Serifs.countSerifses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Serifs', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Serifs> result = Serifs.findAllSerifses();
        Assert.assertNotNull("Find all method for 'Serifs' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Serifs' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SerifsIntegrationTest.testFindSerifsEntries() {
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", dod.getRandomSerifs());
        long count = Serifs.countSerifses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Serifs> result = Serifs.findSerifsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Serifs' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Serifs' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SerifsIntegrationTest.testFlush() {
        Serifs obj = dod.getRandomSerifs();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to provide an identifier", id);
        obj = Serifs.findSerifs(id);
        Assert.assertNotNull("Find method for 'Serifs' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySerifs(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Serifs' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SerifsIntegrationTest.testMergeUpdate() {
        Serifs obj = dod.getRandomSerifs();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to provide an identifier", id);
        obj = Serifs.findSerifs(id);
        boolean modified =  dod.modifySerifs(obj);
        Integer currentVersion = obj.getVersion();
        Serifs merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'Serifs' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SerifsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", dod.getRandomSerifs());
        Serifs obj = dod.getNewTransientSerifs(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Serifs' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Serifs' identifier to be null", obj.getId_());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Serifs' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void SerifsIntegrationTest.testRemove() {
        Serifs obj = dod.getRandomSerifs();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Serifs' failed to provide an identifier", id);
        obj = Serifs.findSerifs(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Serifs' with identifier '" + id + "'", Serifs.findSerifs(id));
    }
    
}
