// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.dip.hakuro.twitserif.domain;

import jp.dip.hakuro.twitserif.domain.Serifs;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Serifs_Roo_Configurable {
    
    declare @type: Serifs: @Configurable;
    
}
